package project_db;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

public class Administrator_Form extends javax.swing.JFrame {

    public Administrator_Form() {
        initComponents();
        this.setLocationRelativeTo(null); //Setting the frame in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartingPageTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ViewTotalExpencesLabel = new javax.swing.JLabel();
        OptionsLabel = new javax.swing.JLabel();
        InsertReturnedPapersLabel = new javax.swing.JLabel();
        ViewTotalExpencesPerWorkerLabel = new javax.swing.JLabel();
        Months2TextField = new javax.swing.JTextField();
        Months1TextField = new javax.swing.JTextField();
        WelcomeLabel = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        MinimizeLabel = new javax.swing.JLabel();
        UsernameAdministratorFormLabel = new javax.swing.JLabel();
        BackLabel = new javax.swing.JLabel();

        StartingPageTextField.setBackground(new java.awt.Color(127, 140, 141));
        StartingPageTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(155, 89, 182));

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));

        ViewTotalExpencesLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ViewTotalExpencesLabel.setForeground(new java.awt.Color(255, 255, 255));
        ViewTotalExpencesLabel.setText("View total expences. Months:");
        ViewTotalExpencesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewTotalExpencesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewTotalExpencesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewTotalExpencesLabelMouseExited(evt);
            }
        });

        OptionsLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        OptionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        OptionsLabel.setText("Options:");

        InsertReturnedPapersLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        InsertReturnedPapersLabel.setForeground(new java.awt.Color(255, 255, 255));
        InsertReturnedPapersLabel.setText("Insert returned copies.");
        InsertReturnedPapersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertReturnedPapersLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InsertReturnedPapersLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InsertReturnedPapersLabelMouseExited(evt);
            }
        });

        ViewTotalExpencesPerWorkerLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ViewTotalExpencesPerWorkerLabel.setForeground(new java.awt.Color(255, 255, 255));
        ViewTotalExpencesPerWorkerLabel.setText("View total expenses per worker. Months:");
        ViewTotalExpencesPerWorkerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewTotalExpencesPerWorkerLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewTotalExpencesPerWorkerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewTotalExpencesPerWorkerLabelMouseExited(evt);
            }
        });

        Months2TextField.setBackground(new java.awt.Color(127, 140, 141));
        Months2TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Months1TextField.setBackground(new java.awt.Color(127, 140, 141));
        Months1TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ViewTotalExpencesPerWorkerLabel)
                        .addGap(18, 18, 18)
                        .addComponent(Months2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OptionsLabel)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ViewTotalExpencesLabel)
                        .addGap(18, 18, 18)
                        .addComponent(Months1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InsertReturnedPapersLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertReturnedPapersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewTotalExpencesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(Months1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewTotalExpencesPerWorkerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(Months2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        WelcomeLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome");

        LogoLabel.setFont(new java.awt.Font("Rage Italic", 1, 60)); // NOI18N
        LogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoLabel.setText("A");

        CloseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CloseLabel.setForeground(new java.awt.Color(255, 255, 255));
        CloseLabel.setText("X");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        MinimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MinimizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeLabel.setText("-");
        MinimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseExited(evt);
            }
        });

        UsernameAdministratorFormLabel.setBackground(new java.awt.Color(155, 89, 182));
        UsernameAdministratorFormLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        UsernameAdministratorFormLabel.setForeground(new java.awt.Color(255, 255, 255));

        BackLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BackLabel.setForeground(new java.awt.Color(255, 255, 255));
        BackLabel.setText("<");
        BackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WelcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(UsernameAdministratorFormLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WelcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameAdministratorFormLabel))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTotalExpencesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTotalExpencesLabelMouseClicked
        Administrator_TotalExpences ate = new Administrator_TotalExpences(); //Creating a new JFrame object to the Frame that we will be transfered
        ate.setVisible(true); //Making it visible
        ate.pack(); //Make the size of the JFrame appropriate to fit all the contents
        ate.setLocationRelativeTo(null); //Setting the frame in the center
        ate.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_ViewTotalExpencesLabelMouseClicked

    private void InsertReturnedPapersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertReturnedPapersLabelMouseClicked
        Administrator_Insert ai  = new Administrator_Insert(); //Creating a new JFrame object to the Frame that we will be transfered
        ai.NewspaperNameComboBox.insertItemAt("", 0); //Inserting an empty value in the combo box for the clear operation
        ai.PaperNumberComboBox.insertItemAt("", 0); 
        try{
            Class.forName("com.mysql.jdbc.Driver"); //Specifying the Driver that will be used to connect
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root",""); //Connecting to the database
            String query1 = "{CALL get_paper_number(?)}"; //Writing the SQL Query
            PreparedStatement pstmt1 = con.prepareStatement(query1); //Creating a PreparedStatement for the query
            pstmt1.setString(1, Login.user); //Setting the variable of the query
            ResultSet rs1 = pstmt1.executeQuery(); //and then executing it and saving the result to a ResultSet
            while(rs1.next()){ //While there is a next row
                ai.PaperNumberComboBox.addItem(rs1.getString("number")); //we insert the result to the Combo Box
            }
            String query2 = "{CALL get_newspaper(?)}"; //Doing the same for the next Combo Box
            PreparedStatement pstmt2 = con.prepareStatement(query2);
            pstmt2.setString(1, Login.user);
            ResultSet rs2 = pstmt2.executeQuery();
            while(rs2.next()){
                ai.NewspaperNameComboBox.addItem(rs2.getString("name"));
            }
            con.close(); //Closing the connection when we are done
        }catch(Exception e){System.out.println(e);}
        ai.setVisible(true); // and setting the settings of the JFrame to open properly
        ai.pack();
        ai.setLocationRelativeTo(null);
        ai.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_InsertReturnedPapersLabelMouseClicked

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0); //Exit the system when the Close Label is clicked
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void MinimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED); //Minimize the JFrame when the Minimize Label is clicked
    }//GEN-LAST:event_MinimizeLabelMouseClicked

    private void BackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseClicked
        Login l = new Login(); //Going back to the Login screen when the Back Label is clicked by creating a new object of the JFrame
        l.setVisible(true); //Making it visible
        l.pack(); //Make the size of the JFrame appropriate to fit all the contents
        l.setLocationRelativeTo(null); //Setting the frame in the center
        l.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_BackLabelMouseClicked

    private void ViewTotalExpencesPerWorkerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTotalExpencesPerWorkerLabelMouseClicked
        Administrator_TotalExpencesPerWorker atepw = new Administrator_TotalExpencesPerWorker(); //Creating a new JFrame object to the Frame that we will be transfered
        atepw.setVisible(true); //Making it visible
        atepw.pack(); //Make the size of the JFrame appropriate to fit all the contents
        atepw.setLocationRelativeTo(null); //Setting the frame in the center
        atepw.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_ViewTotalExpencesPerWorkerLabelMouseClicked

    private void InsertReturnedPapersLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertReturnedPapersLabelMouseEntered
        InsertReturnedPapersLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_InsertReturnedPapersLabelMouseEntered

    private void InsertReturnedPapersLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertReturnedPapersLabelMouseExited
        InsertReturnedPapersLabel.setForeground(Color.white);
    }//GEN-LAST:event_InsertReturnedPapersLabelMouseExited

    private void ViewTotalExpencesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTotalExpencesLabelMouseEntered
        ViewTotalExpencesLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_ViewTotalExpencesLabelMouseEntered

    private void ViewTotalExpencesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTotalExpencesLabelMouseExited
        ViewTotalExpencesLabel.setForeground(Color.white);
    }//GEN-LAST:event_ViewTotalExpencesLabelMouseExited

    private void ViewTotalExpencesPerWorkerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTotalExpencesPerWorkerLabelMouseEntered
        ViewTotalExpencesPerWorkerLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_ViewTotalExpencesPerWorkerLabelMouseEntered

    private void ViewTotalExpencesPerWorkerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTotalExpencesPerWorkerLabelMouseExited
        ViewTotalExpencesPerWorkerLabel.setForeground(Color.white);
    }//GEN-LAST:event_ViewTotalExpencesPerWorkerLabelMouseExited

    private void BackLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseEntered
        BackLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BackLabelMouseEntered

    private void BackLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseExited
        BackLabel.setForeground(Color.white);
    }//GEN-LAST:event_BackLabelMouseExited

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setForeground(Color.red);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        CloseLabel.setForeground(Color.white);
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseEntered
        MinimizeLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_MinimizeLabelMouseEntered

    private void MinimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseExited
        MinimizeLabel.setForeground(Color.white);
    }//GEN-LAST:event_MinimizeLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel InsertReturnedPapersLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel MinimizeLabel;
    public static javax.swing.JTextField Months1TextField;
    public static javax.swing.JTextField Months2TextField;
    private javax.swing.JLabel OptionsLabel;
    private javax.swing.JTextField StartingPageTextField;
    public javax.swing.JLabel UsernameAdministratorFormLabel;
    private javax.swing.JLabel ViewTotalExpencesLabel;
    private javax.swing.JLabel ViewTotalExpencesPerWorkerLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
