package project_db;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

public class ChiefEditor_Form extends javax.swing.JFrame {

    /**
     * Creates new form ChiefEditor_Form
     */
    public ChiefEditor_Form() {
        initComponents(); 
        this.setLocationRelativeTo(null); //Setting the frame in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Months1TextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        SetArticlePrioritiesLabel = new javax.swing.JLabel();
        OptionsLabel = new javax.swing.JLabel();
        CheckArticlesLabel = new javax.swing.JLabel();
        InsertArticleLabel = new javax.swing.JLabel();
        InsertCategoryLabel = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        MinimizeLabel = new javax.swing.JLabel();
        UsernameChiefEditorFormLabel = new javax.swing.JLabel();
        BackLabel = new javax.swing.JLabel();

        Months1TextField.setBackground(new java.awt.Color(127, 140, 141));
        Months1TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(155, 89, 182));

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));

        SetArticlePrioritiesLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SetArticlePrioritiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        SetArticlePrioritiesLabel.setText("Set article priorities.");
        SetArticlePrioritiesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetArticlePrioritiesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SetArticlePrioritiesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SetArticlePrioritiesLabelMouseExited(evt);
            }
        });

        OptionsLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        OptionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        OptionsLabel.setText("Options:");

        CheckArticlesLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        CheckArticlesLabel.setForeground(new java.awt.Color(255, 255, 255));
        CheckArticlesLabel.setText("Check articles.");
        CheckArticlesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckArticlesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckArticlesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CheckArticlesLabelMouseExited(evt);
            }
        });

        InsertArticleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        InsertArticleLabel.setForeground(new java.awt.Color(255, 255, 255));
        InsertArticleLabel.setText("Insert a new article.");
        InsertArticleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertArticleLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InsertArticleLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InsertArticleLabelMouseExited(evt);
            }
        });

        InsertCategoryLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        InsertCategoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        InsertCategoryLabel.setText("Insert a new category.");
        InsertCategoryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertCategoryLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InsertCategoryLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InsertCategoryLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsertCategoryLabel)
                    .addComponent(OptionsLabel)
                    .addComponent(SetArticlePrioritiesLabel)
                    .addComponent(CheckArticlesLabel)
                    .addComponent(InsertArticleLabel))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckArticlesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(SetArticlePrioritiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertArticleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        WelcomeLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome");

        LogoLabel.setFont(new java.awt.Font("Rage Italic", 1, 60)); // NOI18N
        LogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoLabel.setText("C");

        CloseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CloseLabel.setForeground(new java.awt.Color(255, 255, 255));
        CloseLabel.setText("X");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        MinimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MinimizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeLabel.setText("-");
        MinimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseExited(evt);
            }
        });

        UsernameChiefEditorFormLabel.setBackground(new java.awt.Color(155, 89, 182));
        UsernameChiefEditorFormLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        UsernameChiefEditorFormLabel.setForeground(new java.awt.Color(255, 255, 255));

        BackLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BackLabel.setForeground(new java.awt.Color(255, 255, 255));
        BackLabel.setText("<");
        BackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WelcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(UsernameChiefEditorFormLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WelcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameChiefEditorFormLabel))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetArticlePrioritiesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetArticlePrioritiesLabelMouseClicked
        ChiefEditor_SetPriorities cesp = new ChiefEditor_SetPriorities(); //Creating a new JFrame object to the Frame that we will be transfered
        cesp.PaperNumberComboBox.insertItemAt("", 0); //Inserting empty values to our combo box for the cancel operation
        cesp.PathComboBox.insertItemAt("", 0);
        try{
            Class.forName("com.mysql.jdbc.Driver"); //Specifying the Driver that will be used to connect
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root",""); //Connecting to the database
            String query1 = "{CALL get_path_c(?)}"; //Calling the SQL Stored Procedure
            PreparedStatement pstmt1 = con.prepareStatement(query1); //Creating a PreparedStatement for the query
            pstmt1.setString(1, Login.user); //Setting the variable of the query
            ResultSet rs1 = pstmt1.executeQuery(); //and then executing it and saving the result to a ResultSet
            while(rs1.next()){ //While there is a next row
                cesp.PathComboBox.addItem(rs1.getString("path")); //we insert the result to the Combo Box
            }
            String query2 = "{CALL get_paper_number(?)}"; //Doing the same for the next Combo Box
            PreparedStatement pstmt2 = con.prepareStatement(query2); 
            pstmt2.setString(1, Login.user);
            ResultSet rs2 = pstmt2.executeQuery();
            while(rs2.next()){
                cesp.PaperNumberComboBox.addItem(rs2.getString("number"));
            }
            con.close(); //Closing the connection when we are done
        }catch(Exception e){System.out.println(e);}
        cesp.setVisible(true); // and setting the settings of the JFrame to open properly
        cesp.pack();
        cesp.setLocationRelativeTo(null);
        cesp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_SetArticlePrioritiesLabelMouseClicked

    private void CheckArticlesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckArticlesLabelMouseClicked
        ChiefEditor_CheckArticles ceca  = new ChiefEditor_CheckArticles(); //Creating a new JFrame object to the Frame that we will be transfered
        ceca.PathComboBox.insertItemAt("", 0); //Inserting empty values to our combo box for the cancel operation
        ceca.StateComboBox.insertItemAt("", 0);
        ceca.StateComboBox.setSelectedItem("");
        try{
            Class.forName("com.mysql.jdbc.Driver"); //Specifying the Driver that will be used to connect
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root",""); //Connecting to the database
            String query = "{CALL get_path_c(?)}"; //Writing the SQL Query
            PreparedStatement pstmt = con.prepareStatement(query); //Creating a PreparedStatement for the query
            pstmt.setString(1, Login.user); //Setting the variable of the query
            ResultSet rs = pstmt.executeQuery(); //and then executing it and saving the result to a ResultSet
            while(rs.next()){ //While there is a next row
                ceca.PathComboBox.addItem(rs.getString("path")); //we insert the result to the Combo Box
            }
            con.close(); //Closing the connection when we are done
        }catch(Exception e){System.out.println(e);}
        ceca.setVisible(true); //Making it visible
        ceca.pack(); //Make the size of the JFrame appropriate to fit all the contents
        ceca.setLocationRelativeTo(null); //Setting the frame in the center
        ceca.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_CheckArticlesLabelMouseClicked

    private void InsertArticleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertArticleLabelMouseClicked
        ChiefEditor_Insert cfi = new ChiefEditor_Insert(); //Creating a new JFrame object to the Frame that we will be transfered
        cfi.setVisible(true); //Making it visible
        cfi.pack(); //Make the size of the JFrame appropriate to fit all the contents
        cfi.setLocationRelativeTo(null); //Setting the frame in the center
        cfi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_InsertArticleLabelMouseClicked

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0); //Exit the system when the Close Label is clicked
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void MinimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED); //Minimize the JFrame when the Minimize Label is clicked
    }//GEN-LAST:event_MinimizeLabelMouseClicked

    private void BackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseClicked
        Login l = new Login(); //Going back to the Login screen when the Back Label is clicked by creating a new object of the JFrame
        l.setVisible(true); //Making it visible
        l.pack(); //Make the size of the JFrame appropriate to fit all the contents
        l.setLocationRelativeTo(null); //Setting the frame in the center
        l.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_BackLabelMouseClicked

    private void InsertCategoryLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertCategoryLabelMouseClicked
        ChiefEditor_InsertCategory ceic = new ChiefEditor_InsertCategory(); //Creating a new JFrame object to the Frame that we will be transfered
        ceic.setVisible(true); //Making it visible
        ceic.pack(); //Make the size of the JFrame appropriate to fit all the contents
        ceic.setLocationRelativeTo(null); //Setting the frame in the center
        ceic.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_InsertCategoryLabelMouseClicked

    private void CheckArticlesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckArticlesLabelMouseEntered
        CheckArticlesLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_CheckArticlesLabelMouseEntered

    private void CheckArticlesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckArticlesLabelMouseExited
        CheckArticlesLabel.setForeground(Color.white);
    }//GEN-LAST:event_CheckArticlesLabelMouseExited

    private void SetArticlePrioritiesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetArticlePrioritiesLabelMouseEntered
        SetArticlePrioritiesLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_SetArticlePrioritiesLabelMouseEntered

    private void SetArticlePrioritiesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetArticlePrioritiesLabelMouseExited
        SetArticlePrioritiesLabel.setForeground(Color.white);
    }//GEN-LAST:event_SetArticlePrioritiesLabelMouseExited

    private void InsertArticleLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertArticleLabelMouseEntered
        InsertArticleLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_InsertArticleLabelMouseEntered

    private void InsertArticleLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertArticleLabelMouseExited
        InsertArticleLabel.setForeground(Color.white);
    }//GEN-LAST:event_InsertArticleLabelMouseExited

    private void InsertCategoryLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertCategoryLabelMouseEntered
        InsertCategoryLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_InsertCategoryLabelMouseEntered

    private void InsertCategoryLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertCategoryLabelMouseExited
        InsertCategoryLabel.setForeground(Color.white);
    }//GEN-LAST:event_InsertCategoryLabelMouseExited

    private void BackLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseEntered
        BackLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BackLabelMouseEntered

    private void BackLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseExited
        BackLabel.setForeground(Color.white);
    }//GEN-LAST:event_BackLabelMouseExited

    private void MinimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseEntered
        MinimizeLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_MinimizeLabelMouseEntered

    private void MinimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseExited
        MinimizeLabel.setForeground(Color.white);
    }//GEN-LAST:event_MinimizeLabelMouseExited

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setForeground(Color.red);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        CloseLabel.setForeground(Color.white);
    }//GEN-LAST:event_CloseLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiefEditor_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiefEditor_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiefEditor_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiefEditor_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiefEditor_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLabel;
    private javax.swing.JLabel CheckArticlesLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel InsertArticleLabel;
    private javax.swing.JLabel InsertCategoryLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel MinimizeLabel;
    public static javax.swing.JTextField Months1TextField;
    private javax.swing.JLabel OptionsLabel;
    private javax.swing.JLabel SetArticlePrioritiesLabel;
    public javax.swing.JLabel UsernameChiefEditorFormLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
