package project_db;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

public class PublisherForm extends javax.swing.JFrame {

    /**
     * Creates new form PublisherForm
     */
    public PublisherForm() {
        initComponents();
        this.setLocationRelativeTo(null); //Setting the frame in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        SetPaperCopiesLabel = new javax.swing.JLabel();
        OptionsLabel = new javax.swing.JLabel();
        EditNewspaperLabel = new javax.swing.JLabel();
        SetChiefEditorLabel = new javax.swing.JLabel();
        ViewPaperSalesLabel = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        MinimizeLabel = new javax.swing.JLabel();
        UsernamePublisherFormLabel = new javax.swing.JLabel();
        BackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(155, 89, 182));

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));

        SetPaperCopiesLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SetPaperCopiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        SetPaperCopiesLabel.setText("Set papers copies.");
        SetPaperCopiesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetPaperCopiesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SetPaperCopiesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SetPaperCopiesLabelMouseExited(evt);
            }
        });

        OptionsLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        OptionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        OptionsLabel.setText("Options:");

        EditNewspaperLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        EditNewspaperLabel.setForeground(new java.awt.Color(255, 255, 255));
        EditNewspaperLabel.setText("Edit newspapers.");
        EditNewspaperLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditNewspaperLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditNewspaperLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditNewspaperLabelMouseExited(evt);
            }
        });

        SetChiefEditorLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SetChiefEditorLabel.setForeground(new java.awt.Color(255, 255, 255));
        SetChiefEditorLabel.setText("Set Chief Editor.");
        SetChiefEditorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetChiefEditorLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SetChiefEditorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SetChiefEditorLabelMouseExited(evt);
            }
        });

        ViewPaperSalesLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ViewPaperSalesLabel.setForeground(new java.awt.Color(255, 255, 255));
        ViewPaperSalesLabel.setText("View paper sales.");
        ViewPaperSalesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewPaperSalesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewPaperSalesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewPaperSalesLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OptionsLabel)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EditNewspaperLabel)
                        .addComponent(SetPaperCopiesLabel)
                        .addComponent(SetChiefEditorLabel)
                        .addComponent(ViewPaperSalesLabel)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditNewspaperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(SetPaperCopiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(SetChiefEditorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewPaperSalesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(94, 94, 94))
        );

        WelcomeLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome");

        LogoLabel.setFont(new java.awt.Font("Rage Italic", 1, 60)); // NOI18N
        LogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoLabel.setText("P");

        CloseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CloseLabel.setForeground(new java.awt.Color(255, 255, 255));
        CloseLabel.setText("X");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseLabelMousePressed(evt);
            }
        });

        MinimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MinimizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeLabel.setText("-");
        MinimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseExited(evt);
            }
        });

        UsernamePublisherFormLabel.setBackground(new java.awt.Color(155, 89, 182));
        UsernamePublisherFormLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        UsernamePublisherFormLabel.setForeground(new java.awt.Color(255, 255, 255));

        BackLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BackLabel.setForeground(new java.awt.Color(255, 255, 255));
        BackLabel.setText("<");
        BackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WelcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(UsernamePublisherFormLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WelcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernamePublisherFormLabel))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetPaperCopiesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetPaperCopiesLabelMouseClicked
        Publisher_SetCopies psc = new Publisher_SetCopies(); //Creating a new JFrame object to the Frame that we will be transfered
        psc.PaperNumberComboBox.insertItemAt("", 0); //Inserting empty values to our combo box for the cancel operation
        psc.NewspaperNameComboBox.insertItemAt("", 0);
        try{
            Class.forName("com.mysql.jdbc.Driver"); //Specifying the Driver that will be used to connect
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root",""); //Connecting to the database
            String query1 = "{CALL get_paper_number(?)}"; //Calling the SQL Stored Procedure
            PreparedStatement pstmt1 = con.prepareStatement(query1); //Creating a PreparedStatement for the query
            pstmt1.setString(1, Login.user); //Setting the variable of the query
            ResultSet rs1 = pstmt1.executeQuery(); //and then executing it and saving the result to a ResultSet
            while(rs1.next()){ //While there is a next row
                psc.PaperNumberComboBox.addItem(rs1.getString("number")); //we insert the result to the Combo Box
            }
            String query2 = "{CALL get_newspaper(?)}"; //Doing the same for the next Combo Box
            PreparedStatement pstmt2 = con.prepareStatement(query2);
            pstmt2.setString(1, Login.user);
            ResultSet rs2 = pstmt2.executeQuery();
            while(rs2.next()){
                psc.NewspaperNameComboBox.addItem(rs2.getString("name"));
            }
            con.close(); //Closing the connection when we are done
        }catch(Exception e){System.out.println(e);}
        psc.setVisible(true); // and setting the settings of the JFrame to open properly
        psc.pack();
        psc.setLocationRelativeTo(null);
        psc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        psc.UsernamePublisherSetCopies.setText(Login.user);
        this.dispose();
    }//GEN-LAST:event_SetPaperCopiesLabelMouseClicked

    private void EditNewspaperLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditNewspaperLabelMouseClicked
        Publisher_EditNewspaper pen = new Publisher_EditNewspaper(); //Creating a new JFrame object to the Frame that we will be transfered
        pen.NewspaperNameComboBox.insertItemAt("", 0); //Inserting empty values to our combo box for the cancel operation
        pen.FrequencyComboBox.insertItemAt("", 0);
        pen.FrequencyComboBox.setSelectedItem("");
        try{
            Class.forName("com.mysql.jdbc.Driver"); //Specifying the Driver that will be used to connect
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root",""); //Connecting to the database
            String query = "{CALL get_newspaper(?)}"; //Calling the SQL Stored Procedure
            PreparedStatement pstmt = con.prepareStatement(query); //Creating a PreparedStatement for the query
            pstmt.setString(1, Login.user); //Setting the variable of the query
            ResultSet rs = pstmt.executeQuery(); //and then executing it and saving the result to a ResultSet
            while(rs.next()){ //While there is a next row
                pen.NewspaperNameComboBox.addItem(rs.getString("name")); //we insert the result to the Combo Box
            }
            con.close(); //Closing the connection when we are done
        }catch(Exception e){System.out.println(e);}
        pen.setVisible(true); // and setting the settings of the JFrame to open properly
        pen.pack();
        pen.setLocationRelativeTo(null);
        pen.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pen.UsernamePublisherEditNewspaper.setText(Login.user);
        this.dispose();
    }//GEN-LAST:event_EditNewspaperLabelMouseClicked

    private void SetChiefEditorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetChiefEditorLabelMouseClicked
        Publisher_SetChiefEditor psce = new Publisher_SetChiefEditor(); //Creating a new JFrame object to the Frame that we will be transfered
        psce.NewspaperNameComboBox.insertItemAt("", 0); //Inserting empty values to our combo box for the cancel operation
        psce.JournalistComboBox.insertItemAt("", 0);
        try{
            Class.forName("com.mysql.jdbc.Driver"); //Specifying the Driver that will be used to connect
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root",""); //Connecting to the database
            String query1 = "{CALL get_newspaper(?)}"; //Calling the SQL Stored Procedure
            PreparedStatement pstmt1 = con.prepareStatement(query1); //Creating a PreparedStatement for the query
            pstmt1.setString(1, Login.user); //Setting the variable of the query
            ResultSet rs1 = pstmt1.executeQuery(); //and then executing it and saving the result to a ResultSet
            while(rs1.next()){ //While there is a next row
                psce.NewspaperNameComboBox.addItem(rs1.getString("name")); //we insert the result to the Combo Box
            }
            String query2 = "{CALL get_journalists_p(?)}"; //We do the same for the other combo box
            PreparedStatement pstmt2 = con.prepareStatement(query2);
            pstmt2.setString(1, Login.user);
            ResultSet rs2 = pstmt2.executeQuery();
            while(rs2.next()){
                psce.JournalistComboBox.addItem(rs2.getString("email"));
            }
            con.close(); con.close(); //Closing the connection when we are done
        }catch(Exception e){System.out.println(e);}
        psce.setVisible(true); // and setting the settings of the JFrame to open properly
        psce.pack();
        psce.setLocationRelativeTo(null);
        psce.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        psce.UsernamePublisherSetChiefEditor.setText(Login.user);
        this.dispose();
    }//GEN-LAST:event_SetChiefEditorLabelMouseClicked

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0); //Exit the system when the Close Label is clicked
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void MinimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED); //Minimize the JFrame when the Minimize Label is clicked
    }//GEN-LAST:event_MinimizeLabelMouseClicked

    private void BackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseClicked
        Login l = new Login(); //Going back to the Login screen when the Back Label is clicked by creating a new object of the JFrame
        l.setVisible(true); //Making it visible
        l.pack(); //Make the size of the JFrame appropriate to fit all the contents
        l.setLocationRelativeTo(null); //Setting the frame in the center
        l.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_BackLabelMouseClicked

    private void ViewPaperSalesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPaperSalesLabelMouseClicked
        Publisher_PaperSalesResults ppsr = new Publisher_PaperSalesResults(); //Creating a new JFrame object to the Frame that we will be transfered
        ppsr.setVisible(true); //Making it visible
        ppsr.pack(); //Make the size of the JFrame appropriate to fit all the contents
        ppsr.setLocationRelativeTo(null); //Setting the frame in the center
        ppsr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Specifying that the close button, when pressed, should exit the application
        ppsr.UsernamePublisherResultsLabel.setText(Login.user); //Setting the text of the Username Label to the user that logged in
        this.dispose(); //Closing this frame
    }//GEN-LAST:event_ViewPaperSalesLabelMouseClicked

    private void EditNewspaperLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditNewspaperLabelMouseEntered
        EditNewspaperLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_EditNewspaperLabelMouseEntered

    private void EditNewspaperLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditNewspaperLabelMouseExited
        EditNewspaperLabel.setForeground(Color.white);
    }//GEN-LAST:event_EditNewspaperLabelMouseExited

    private void SetPaperCopiesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetPaperCopiesLabelMouseEntered
        SetPaperCopiesLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_SetPaperCopiesLabelMouseEntered

    private void SetPaperCopiesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetPaperCopiesLabelMouseExited
        SetPaperCopiesLabel.setForeground(Color.white);
    }//GEN-LAST:event_SetPaperCopiesLabelMouseExited

    private void SetChiefEditorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetChiefEditorLabelMouseEntered
        SetChiefEditorLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_SetChiefEditorLabelMouseEntered

    private void SetChiefEditorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetChiefEditorLabelMouseExited
        SetChiefEditorLabel.setForeground(Color.white);
    }//GEN-LAST:event_SetChiefEditorLabelMouseExited

    private void ViewPaperSalesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPaperSalesLabelMouseEntered
        ViewPaperSalesLabel.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_ViewPaperSalesLabelMouseEntered

    private void ViewPaperSalesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPaperSalesLabelMouseExited
        ViewPaperSalesLabel.setForeground(Color.white);
    }//GEN-LAST:event_ViewPaperSalesLabelMouseExited

    private void BackLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseEntered
        BackLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BackLabelMouseEntered

    private void BackLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseExited
        BackLabel.setForeground(Color.white);
    }//GEN-LAST:event_BackLabelMouseExited

    private void MinimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseEntered
        MinimizeLabel.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_MinimizeLabelMouseEntered

    private void MinimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseExited
        MinimizeLabel.setForeground(Color.white);
    }//GEN-LAST:event_MinimizeLabelMouseExited

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setForeground(Color.red);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseLabelMousePressed

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        CloseLabel.setForeground(Color.white);
    }//GEN-LAST:event_CloseLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublisherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublisherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublisherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublisherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublisherForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel EditNewspaperLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel MinimizeLabel;
    private javax.swing.JLabel OptionsLabel;
    private javax.swing.JLabel SetChiefEditorLabel;
    private javax.swing.JLabel SetPaperCopiesLabel;
    public static javax.swing.JLabel UsernamePublisherFormLabel;
    private javax.swing.JLabel ViewPaperSalesLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
